name: "Run E2E Tests"
on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
  push:
    branches:
      - main
      - release-*
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    continue-on-error: false
    steps:
      - uses: michalskrivanek/jumpstarter-e2e@main
        with:
          controller-url: jumpstarter-dev/jumpstarter-controller
          controller-ref: main
          jumpstarter-url: michalskrivanek/jumpstarter
          jumpstarter-ref: ${{ github.event.inputs.branch }}
